//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizontalList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HorizontalList.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Products.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Products.
        /// </summary>
        public static string btn_manageproduct {
            get {
                return ResourceManager.GetString("btn_manageproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en:English,de:Deutsch.
        /// </summary>
        public static string languageselection {
            get {
                return ResourceManager.GetString("languageselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string txt_addProduct {
            get {
                return ResourceManager.GetString("txt_addProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string txt_addtocart {
            get {
                return ResourceManager.GetString("txt_addtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string txt_buy {
            get {
                return ResourceManager.GetString("txt_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Products.
        /// </summary>
        public static string txt_buyproducts {
            get {
                return ResourceManager.GetString("txt_buyproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CART.
        /// </summary>
        public static string txt_cart {
            get {
                return ResourceManager.GetString("txt_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        public static string txt_changeimage {
            get {
                return ResourceManager.GetString("txt_changeimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        public static string txt_description {
            get {
                return ResourceManager.GetString("txt_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string txt_editproduct {
            get {
                return ResourceManager.GetString("txt_editproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Name....
        /// </summary>
        public static string txt_enterproductname {
            get {
                return ResourceManager.GetString("txt_enterproductname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Price....
        /// </summary>
        public static string txt_enterproductprice {
            get {
                return ResourceManager.GetString("txt_enterproductprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Description....
        /// </summary>
        public static string txt_enterproducttool {
            get {
                return ResourceManager.GetString("txt_enterproducttool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Total Items....
        /// </summary>
        public static string txt_entertotaltool {
            get {
                return ResourceManager.GetString("txt_entertotaltool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift For.
        /// </summary>
        public static string txt_gift_for {
            get {
                return ResourceManager.GetString("txt_gift_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift For  :.
        /// </summary>
        public static string txt_giftforaddedit {
            get {
                return ResourceManager.GetString("txt_giftforaddedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image :.
        /// </summary>
        public static string txt_image {
            get {
                return ResourceManager.GetString("txt_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Products.
        /// </summary>
        public static string txt_manageproduct {
            get {
                return ResourceManager.GetString("txt_manageproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string txt_nameaddedit {
            get {
                return ResourceManager.GetString("txt_nameaddedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocassion.
        /// </summary>
        public static string txt_ocassion {
            get {
                return ResourceManager.GetString("txt_ocassion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocassion :.
        /// </summary>
        public static string txt_ocassionaddedit {
            get {
                return ResourceManager.GetString("txt_ocassionaddedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        public static string txt_price {
            get {
                return ResourceManager.GetString("txt_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Product.
        /// </summary>
        public static string txt_search {
            get {
                return ResourceManager.GetString("txt_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string txt_sortby {
            get {
                return ResourceManager.GetString("txt_sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount : €.
        /// </summary>
        public static string txt_totalamount {
            get {
                return ResourceManager.GetString("txt_totalamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items :.
        /// </summary>
        public static string txt_totalitems {
            get {
                return ResourceManager.GetString("txt_totalitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string txt_uploadimage {
            get {
                return ResourceManager.GetString("txt_uploadimage", resourceCulture);
            }
        }
    }
}
